spring.application.name=reservation-system
# 1. DBへの接続設定（メモリ上に 'testdb' という名前で作る）
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. H2 Consoleの設定（ブラウザでDBの中身が見れるツール）
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. JPAの設定（起動時にEntityからテーブルを自動作成する）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. JPA(Hibernate)がテーブルを作った後に data.sql を実行するように指示する
spring.jpa.defer-datasource-initialization=true

# 5. 起動時に必須でsqlを実行
spring.sql.init.mode=always

